version: "3.9"

services:
  nextjs:
    image: on-smart
    container_name: onsmart
    restart: always
    ports:
      - "80:3000"
    environment:
      PORT: 3000
      HOSTNAME: "0.0.0.0"

      BETTER_AUTH_SECRET: "O4stYhijCskqztjIaDrgSK6IQ7XqscCK"
      BETTER_AUTH_URL: "http://env-1595718.it1.eur.aruba.jenv-aruba.cloud"

      DATABASE_HOST: "31.11.38.12"
      DATABASE_USER: "Sql1902646"
      DATABASE_NAME: "Sql1902646_1"
      DATABASE_PASSWORD: ".9KcyuMKx!pi8TN"
