services:
  mysql:
    image: mysql:8.0
    container_name: onsmart-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onsmart_dev
      MYSQL_USER: onsmart
      MYSQL_PASSWORD: onsmart
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
