name: Build & Deploy to Aruba Cloud

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      #   - name: Login to Docker Hub
      #     uses: docker/login-action@v3
      #     with:
      #       username: ${{ secrets.DOCKERHUB_USERNAME }}
      #       password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t serhiioberemchuk/on-smart:latest .

      - name: Push Docker image
        run: |
          docker login -u serhiioberemchuk -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push serhiioberemchuk/on-smart:latest

    #   - name: Trigger Aruba Redeploy
    #     run: |
    #       curl -X POST "${{ secrets.ARUBA_DEPLOY_URL }}"
